video_parameters:
  # video_name: "Pep_Guardiola_explained_why_Chelsea_is_so_good"
  #video_name: "Pep_Guardiola_press_conference"
  #video_name: "Press_conference_guardiola"
  # video_name: "Premier_league_press_conference"
  # video_name: 'mourinho tactics'
  video_name: 'Enzo_Maresca'
  context: "This is a tactic football class video"
